### ISSUE TITLE
Empty Configugration although Config exists

### ISSUE THREAD

**Issue by isntfunny** [MrBrax/TwitchAutomator#549]
**Describe the bug**
Everytime i navigate to the config page `/settings/config` every field is empty. Checking the config file on the file system manually shows that there is an config.

**Expected behavior**
Load the configuration from the config file

**Screenshots**

![Image](https://github.com/user-attachments/assets/47c82d06-c156-48b3-ad8e-65ff4c84c17f)
![Image](https://github.com/user-attachments/assets/aec938e9-7dce-4fc9-94a9-2fe4ad7d53de)

**Server:**
 - Docker Compose:
 ```
version: "3.8"
services:
  web:
    restart: always
    image: mrbrax/twitchautomator:master
    ports:
      - 8082:8080
    volumes:
      - data:/usr/local/share/twitchautomator/data
      - /mnt/Streams:/usr/local/share/twitchautomator/data/storage/
    environment:
      - NODE_ENV=production
      - TCD_ENABLE_FILES_API=1
      - TCD_EXPOSE_LOGS_TO_PUBLIC=1
      - TCD_MIGRATE_OLD_VOD_JSON=0
```

**Comment by BigFlubba** [comment]
Make sure that you copied the Docker Compose file as instructed.
```
version: "3.8"
services:
  web:
    build: .
    image: mrbrax/twitchautomator:master
    ports:
      - "8082:8080"
    volumes:
      - ./data:/usr/local/share/twitchautomator/data
    environment:
      - NODE_ENV=production
      - TCD_ENABLE_FILES_API=0
      - TCD_EXPOSE_LOGS_TO_PUBLIC=0
      - TCD_MIGRATE_OLD_VOD_JSON=0
```

After it builds and starts up your ENV's should look something like this.
```
TCD_MIGRATE_OLD_VOD_JSON=0
NODE_ENV=production
TCD_ENABLE_FILES_API=1
TCD_EXPOSE_LOGS_TO_PUBLIC=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.local/bin
NODE_VERSION=20.18.1
YARN_VERSION=1.22.22
IS_DEV=
VITE_IS_DEV=
BUILD_DATE=
VITE_BUILD_DATE=
TCD_TWITCHDOWNLOADER_PATH=/usr/local/bin/TwitchDownloaderCLI
HOME=/home/node
TCD_BIN_DIR=/usr/local/bin
TCD_FFMPEG_PATH=/usr/bin/ffmpeg
TCD_BIN_PATH_PYTHON=/usr/bin/python
TCD_BIN_PATH_PYTHON3=/usr/bin/python3
TCD_MEDIAINFO_PATH=/usr/bin/mediainfo
TCD_NODE_PATH=/usr/local/bin/node
TCD_DOCKER=1
TCD_WEBSOCKET_ENABLED=1
TCD_SERVER_PORT=8080
TCD_PYTHON_ENABLE_PIPENV=1
```

Also, here are my volume mappings.
Container: `/usr/local/share/twitchautomator/data`
Host: `/home/administrator/livestreamdvr`

If you are trying to save recordings to a NAS, I haven't had any luck with it. If you are able to get it to work, please let me know how, so I can add it to my instance.
